"""empty message

Revision ID: 8e3cd44fd15b
Revises: 55ee0f65b276
Create Date: 2024-04-29 18:10:23.082545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e3cd44fd15b'
down_revision = '55ee0f65b276'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('membership_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descripton', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('descripton')
    )
    op.create_table('membership',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['status_id'], ['membership_status.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('membership')
    op.drop_table('membership_status')
    # ### end Alembic commands ###
