"""added boat tables

Revision ID: bdda50727b99
Revises: 35cb124879f4
Create Date: 2024-05-07 08:38:00.823499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdda50727b99'
down_revision = '35cb124879f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('marina_id', sa.Integer(), nullable=False),
    sa.Column('boat_name', sa.String(), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('draft_feet', sa.Integer(), nullable=False),
    sa.Column('draft_inches', sa.Integer(), nullable=False),
    sa.Column('color_hull', sa.String(), nullable=False),
    sa.Column('color_canvas', sa.String(), nullable=False),
    sa.Column('sail_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marina',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('marina_name', sa.String(), nullable=False),
    sa.Column('waterway', sa.String(), nullable=False),
    sa.Column('tributary_of', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marina')
    op.drop_table('boat')
    # ### end Alembic commands ###
